obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.07, 0.025], [-0.07, 0.025], [-0.07, -0.025], [0.07, -0.025]] #length and width (rectangle approx)
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}
